### ISSUE TITLE
Example Project Request

### ISSUE THREAD

**Issue by kevupton** [intellij-solidity/intellij-solidity#10]
I havent used much of intellij so I am not too familiar with the project setup,

Just wondering if someone could create an example github project while using this plugin, so I can see they way it is done :)

**Comment by SerCeMan** [comment]
Hi, @kevupton!

Intellij solidity is a plugin for the [solidity.readthedocs.io](Solidity) language. It doesn't provide any framework for developing with it. You are, probably, interested in a project providing an easy way to develop apps on solidity. 

I'd recommend you to check out: 
1) Solidity docs: solidity.readthedocs.io
2) https://github.com/web3j/web3j and relevant examples, JVM
3) https://github.com/trufflesuite/truffle and relevant examples, JS

If you want to open any solidity project to understand what plugin provides, you can open https://github.com/OpenZeppelin/zeppelin-solidity project using IntelliJ product with the plugin installed.
