### ISSUE TITLE
"No solc installation found" error if not root

### ISSUE THREAD

**Issue by kincsescsaba** [intellij-solidity/intellij-solidity#100]
If "Use solc from EthereumJ bundle" is checked and I'm not a root user on Linux, then I get "No solc installation found" error from IDEA. If root, no error.

**Comment by mbolotov** [comment]
Hey, @kincsescsaba!

Are there any related errors in the logs?
Could provide them?

**Comment by kincsescsaba** [comment]
This is strange, because all permissions are give on /tmp
Owner and group is root but all permissions are given with chmod 777

**Comment by mbolotov** [comment]
Exception shows it fails when trying to remove the previous solc file.
There may be a running solc process that blocks removing the file.
Could you please check the process?

**Comment by kincsescsaba** [comment]
ps aux | grep solc returns nothing

**Comment by kincsescsaba** [comment]
This seems to be something EthereumJ and Linux specific. I recreated the above error with EthereumJ's SolidityCompiler class. Then I restarted the IDE as root, and the error disappeared. Privileges seem to be OK, but can't be if switching to root makes the error disappear. My understanding of Linux privileges may lack something :\

**Comment by kincsescsaba** [comment]
This `sudo chmod 777 /tmp/solc` solved the problem. Both the file and the source directory needs to have the right privileges.

**Comment by mbolotov** [comment]
`solc` support was removed from the plugin
