### ISSUE TITLE
Support "address payable" for upcoming solidity 0.5.0.

### ISSUE THREAD

**Issue by ekpyron** [intellij-solidity/intellij-solidity#106]
In solidity 0.5.0 we will introduce the ``address payable`` type, see https://github.com/ethereum/solidity/pull/4926 and https://github.com/ethereum/solidity/pull/4911. It would be great to see support for that in the intellij plugin!

The valid use cases should be apparent from the grammar https://github.com/ethereum/solidity/blob/9214c7c34f5e4501a50cb29de964bbf04131f9a3/docs/grammar.txt#L53, e.g. variable declarations of the form ``address payable x;`` will be valid, but e.g. there will be no casts like ``address payable(x)`` and it won't be usable as mapping keys as in ``mapping(address payable => uint)`` (whereas ``mapping(uint => address payable)`` will be valid).

Let me know if you need any further information and thank you in advance!

**Comment by SerCeMan** [comment]
Thanks, support added in https://github.com/intellij-solidity/intellij-solidity/pull/107

**Comment by ekpyron** [comment]
Great, thanks!
