### ISSUE TITLE
Memory leak debugging JS via Chrome.  

### ISSUE THREAD

**Issue by daviddfm** [intellij-solidity/intellij-solidity#129]
I have to reset the editor daily if I'm doing a lot of Chrome based Javascript debugging.  The memory monitor starts at about 500MB but eventually gets to 1500MB and everything gets super slow until I restart the editor.

**Comment by SerCeMan** [comment]
Hi, @daviddfm!

Does it happen only when the IntelliJ solidity plugin turned on? If not then it's better to report the issue on https://youtrack.jetbrains.com/.
