### ISSUE TITLE
Error in highlighting when function name starts with _

### ISSUE THREAD

**Issue by 0v1se** [intellij-solidity/intellij-solidity#131]
![image](https://user-images.githubusercontent.com/32102012/46585566-2b3ce780-ca7b-11e8-9d07-b578b4682869.png)

As you can see, in `_preValidatePurchase` _ is highlighted as error and reference to function is not resolved correctly

**Comment by SerCeMan** [comment]
Thanks, @0v1se! This was a regression after https://github.com/intellij-solidity/intellij-solidity/commit/b547b813f7022104168818342fb32efaeee5885c. 

This should be fixed by https://github.com/intellij-solidity/intellij-solidity/pull/132
