### ISSUE TITLE
Inherited functions not showing up in ethereumJ wrapper

### ISSUE THREAD

**Issue by branaway** [intellij-solidity/intellij-solidity#149]
I was experimenting with the native EthereumJ Wrapper generator and noticed that the generated Java classes do not contain functions in a smart contract's super classes.

**Comment by mbolotov** [comment]
@branaway thanks for this finding. I will look into it

**Comment by 0v1se** [comment]
Hey everyone 
@mbolotov if I get correctly what is needed, then ABI json is the best way to generate wrappers: https://solidity.readthedocs.io/en/develop/abi-spec.html#json

It describes external interface of the smart contract

**Comment by branaway** [comment]
One more thing is that putting all the compressed ABI and Bin in the ContractRepository is not scalable when there are large number of contracts in a project and it makes it too big to navigate.  They ABI and BIN should probably go to their respective classes.

**Comment by mbolotov** [comment]
> One more thing is that putting all the compressed ABI and Bin in the ContractRepository is not scalable when there are large number of contracts in a project and it makes it too big to navigate. They ABI and BIN should probably go to their respective classes.

Hi, @branaway!
Please create a separate issue on this to not forget it.

**Comment by mbolotov** [comment]
wrapper generation was removed from the plugin
