### ISSUE TITLE
Wrong precedence in Expression

### ISSUE THREAD

**Issue by 0v1se** [intellij-solidity/intellij-solidity#156]
`Arbitrator(msg.sender) == appealDisputes[_disputeID].arbitrator`
I think `EqExpression` should go higher than `IndexAccessExpression`

@SerCeMan, pls take a look, I'm not a pro in this

**Comment by SerCeMan** [comment]
Hey, @0v1se!

Thanks for reporting this! Should be fixed in https://github.com/intellij-solidity/intellij-solidity/pull/159
