### ISSUE TITLE
Can't mark mapping as public

### ISSUE THREAD

**Issue by karinchechik** [intellij-solidity/intellij-solidity#162]
I'm using webstorm and when I wrote - 

mapping (uint => uint) public age;

I got an error saying: "'public' unexpected".

**Comment by SerCeMan** [comment]
Hey, @karinchechik!

I tried to reproduce, but I wasn't able to. Which version of the plugin are you using? Could you also please attach the minimal reproducible piece of code that's not correctly parsed?

**Comment by karinchechik** [comment]
@SerCeMan 
Sure, I'm using version 2.1.3 of the plugin, and version 2018.2 of WebStorm.

This is the code:

`
pragma solidity ^0.4.25;

contract modifierage {
    function modifierage(){

        // A mapping to store a user's age:
        mapping (uint => uint) public age; // <= The problem is here. 

        // Modifier that requires this user to be older than a certain age:
        modifier olderThan(uint _age, uint _userId) {
        require(age[_userId] >= _age);
        _;
        }

        // Must be older than 16 to drive a car (in the US, at least).
        // We can call the `olderThan` modifier with arguments like so:
        function driveCar(uint _userId) public olderThan(16, _userId) {
        // Some function logic
        }
    }
}
`

**Comment by 0v1se** [comment]
Hey @karinchechik 
You have an error in your smart contract: your mapping and function are defined inside the constructor. You should define them in the contract body

**Comment by karinchechik** [comment]
@0v1se Thank you! 
I didn't notice I did that.
