### ISSUE TITLE
New -> Smart contract causes out-of-memory error

### ISSUE THREAD

**Issue by eepstein** [intellij-solidity/intellij-solidity#17]
Just installed the latest version of this plugin into the latest IntelliJ release and after trying the New File > Smart Contract from the context menu, the system seemed to hang and then eventually showed an out-of-memory error panel.  My first as a 5+ yr user of IntelliJ on Mac.

**Comment by SerCeMan** [comment]
Hi, @eepstein!

Thank you for the report. Can you take a memory-dump so that I can investigate?

**Comment by eepstein** [comment]
Thanks @SerCeMan !

I was one version behind on IntelliJ and in an existing project.  I've now updated IntelliJ and also started a fresh project and the plugin creates the file and returns immediately. 

CAN'T REPRODUCE.  So will close this ticket.  

(If it does recur I'll re-open.)
