### ISSUE TITLE
Missing keyword "calldata"(version 2.1.4)

### ISSUE THREAD

**Issue by trifist** [intellij-solidity/intellij-solidity#175]
see below:

remix ide:
![image](https://user-images.githubusercontent.com/22070288/50408751-37d60e00-0828-11e9-8f5e-e01c7de98461.png)

intellij:
![image](https://user-images.githubusercontent.com/22070288/50408769-5cca8100-0828-11e9-8f4d-8a60c2e3f6c8.png)

**Comment by SerCeMan** [comment]
Hey, @trifist!

Thank you for the report!
