### ISSUE TITLE
Omitted return parameters

### ISSUE THREAD

**Issue by jchittoda** [intellij-solidity/intellij-solidity#178]
Below is the correct statement where `someFunction` returns 3 parameters.
```
(result1, , ) = someFunction(_tokenHolder, _value, _data);
```

Above statement gives error:
```
'(', ')', ',', '.', <storage location> or Identifier expected, got ','
```

**Comment by SerCeMan** [comment]
Hey, @jchittoda!

Thank you for the report! The issue should be fixed in https://github.com/intellij-solidity/intellij-solidity/commit/18aae18170cffd43899aca466f4f77a7817c0ffa.
