### ISSUE TITLE
Solidity settings

### ISSUE THREAD

**Issue by TENRUTER** [intellij-solidity/intellij-solidity#179]
Hi,all
I am a freshman to ethereum;
pc: win10;
workspace:IDEA Ultimate 2018.3.3
when I set solidity like this and apply
![1](https://user-images.githubusercontent.com/25451308/51685576-8c3bfb80-2029-11e9-8435-d29a9bd62c35.png)
it comes "No Solc installation found".
please help me
appreciate your guidance. :)

**Comment by TENRUTER** [comment]
I download the ethereumj-core from https://bintray.com/ethereum/maven/  .

**Comment by mbolotov** [comment]
Hi, @TENRUTER!
It seems the 'jar' artifact does not contain the solc compiler inside.

So could you please try to download the ' ethereumj-core-1.10.1-RELEASE.zip' file from bintray, extract all the content and set the 'EthereumJ VM path' to the 'lib' directory inside the extracted archive?

**Comment by TENRUTER** [comment]
ty, @mbolotov !
I tryed download the  "ethereumj-core-1.9.1-RELEASE" , and set the VM path to "lib"
like this, but it still warn.
![2](https://user-images.githubusercontent.com/25451308/51734057-56952200-20be-11e9-9fc5-b50057219aa7.png)

Will there be any other solution?
thanks anyway

**Comment by mbolotov** [comment]
Oh, I just noticed you have no 'Use Solc from EthereumJ bundle' box checked. This way the plugin will use solc provided by 'Standalone Solc path' that is empty in your case. 
So you can either check the box or enter a path to the standalone solc compiler.

**Comment by TENRUTER** [comment]
@mbolotov thanks for your patience
I don't understand how to install a solc compiler. Hope for your guidance.

I download solidity-windows.zip from https://github.com/ethereum/solidity/releases ;
And add the directory to System environment variable.
It didn't work.

Another, I use Git getting the source code. 
Still didn‘t figure it out.
Thanks again.

**Comment by mbolotov** [comment]
You don't need to add any system variables.
Just add the solc path to the corresponding field:
![image](https://user-images.githubusercontent.com/19785715/51792126-50866a80-21be-11e9-8174-8f906ca48e1c.png)

**Comment by TENRUTER** [comment]
@mbolotov thanks!
Finally, HAPPY to finish the Compile and Run!
Would you please show me the settings of Java interop in Solidity settings?
I wanna know how each option will affect the project, such as "base package" and "Automatically add EthereumJ dependency to each module", and "Style".
Or as I am a beginner, I could just use the default settings.
thanks a lot

**Comment by mbolotov** [comment]
@TENRUTER , as for the 'Java interop' options - the rule is simple: if you don't need to call solidity from java, leave the 'Generate...' checkbox not checked. I guess you don't, right?

**Comment by TENRUTER** [comment]
@mbolotov 
You are right, I don't need.
thx!
