### ISSUE TITLE
support for scientific number notation

### ISSUE THREAD

**Issue by apetersson** [intellij-solidity/intellij-solidity#18]
good code is red:

uint256 pointMultiplier2 = 10e18; 

see also https://solidity.readthedocs.io/en/develop/types.html?highlight=scientific

**Comment by SerCeMan** [comment]
Hi, @apetersson!

Thank you for the report. The problem has already been fixed, https://github.com/intellij-solidity/intellij-solidity/pull/15. The new plugin version will be released once it is approved, https://plugins.jetbrains.com/plugin/9475-intellij-solidity/update/38365.

**Comment by apetersson** [comment]
good to know, just didn't see it on the open issues. patiently awaiting the update then ;)
