### ISSUE TITLE
Add inner block indentation

### ISSUE THREAD

**Issue by hvarakhobava** [intellij-solidity/intellij-solidity#19]
Please add caret shift after hitting enter to start child block. Now the caret is indented at the same position as a parent block. I have to press Tab every time I start to write a new inner block. 

For example:
```
function test() private returns (uint) {
    if (amount < 0) {
    //caret is here
    }
}
```
Expected:
```
function test() private returns (uint) {
    if (amount < 0) {
        //caret is here
    }
}
```

**Comment by SerCeMan** [comment]
Hey, @hvarakhobava! 

Thank you for the report. The feature is implemented now, https://github.com/intellij-solidity/intellij-solidity/commit/56dfb2dffc7cd68e79f5954baee3f860ddfbe076#diff-31f93a2874e6408e22740a33be422175.

**Comment by SerCeMan** [comment]
@hvarakhobava 

On the same topic, contributions are always welcome! And adding a few more tests with cases that are important for your is a great way to start! 

Please reach out to me if you decide to help and you need any guidance with the setup/running/code/etc...

**Comment by hvarakhobava** [comment]
@SerCeMan , thank you so much for the implementation!
