### ISSUE TITLE
Add support comment syntax natspec format

### ISSUE THREAD

**Issue by 4val0v** [intellij-solidity/intellij-solidity#190]
Hello, not enough comment syntax support.
https://solidity.readthedocs.io/en/develop/natspec-format.html

**Comment by passabilities** [comment]
Bump on this.

**Comment by maximebrugel** [comment]
Need this !

**Comment by SerCeMan** [comment]
Hey, folks! Thanks for reporting this! The support for natspec should be available in the next version (https://github.com/intellij-solidity/intellij-solidity/pull/247, https://github.com/intellij-solidity/intellij-solidity/pull/248). 
<img width="709" alt="Screen Shot 2021-09-25 at 2 13 01 pm" src="https://user-images.githubusercontent.com/1780970/134757522-0863c137-40a2-4c75-ba27-375740c8b439.png">
