### ISSUE TITLE
Solidity v0.6.x support

### ISSUE THREAD

**Issue by stanislaw-glogowski** [intellij-solidity/intellij-solidity#193]
Any plans for solidity 0.6 support?
https://github.com/ethereum/solidity/releases/tag/v0.6.2

**Comment by sherazarshad813** [comment]
second this.

**Comment by patitonar** [comment]
Any updates on this issue?

**Comment by SerCeMan** [comment]
Hey, folks! There is initial support for 0.6 in the new version, https://plugins.jetbrains.com/plugin/9475-intellij-solidity/versions/stable/94136, you can download and try! 🚀 

Please open individual issues for every separate compatibility problem that you're facing :)
