### ISSUE TITLE
... expected, got bytes32

### ISSUE THREAD

**Issue by chebykin** [intellij-solidity/intellij-solidity#199]
It seems that the new v2.2.0 can't digest `bytes32` storage declarations. This code raises an error for me:

```solidity
contract Foo {
  address internal ZERO_ADDRESS = address(0);

  bytes32 public GGR = bytes32("GGR");
}
```

The error is `<number type>, <type name>, constructor, enum, event, function, import, modifier, pragma, struct, using or '}' expected, got 'bytes32'`

While this code don't:

```solidity
contract Foo {
  address internal ZERO_ADDRESS = address(0);

  uint256 public GGR = uint256("GGR");
}
```

Can reproduce it on Pycharm 2020.2 EAP and IDEA 2020.2 EAP.

**Comment by SerCeMan** [comment]
Thanks for reporting, should be fixed in https://github.com/intellij-solidity/intellij-solidity/commit/2cbfb9e5028245e01ec2c1dab5c65c4df5da3d3e.
