### ISSUE TITLE
lint error on override keyword (ver 2.3.1) cannot format.

### ISSUE THREAD

**Issue by dexcell** [intellij-solidity/intellij-solidity#207]
<img width="388" alt="Screen Shot 2020-09-19 at 23 54 44" src="https://user-images.githubusercontent.com/41800/93672241-871ba200-fad3-11ea-9537-4a0d1f13c29f.png">

https://solidity.readthedocs.io/en/v0.6.0/contracts.html#index-17
<img width="751" alt="Screen Shot 2020-09-19 at 23 55 13" src="https://user-images.githubusercontent.com/41800/93672246-94d12780-fad3-11ea-84a7-59155b664619.png">

**Comment by SerCeMan** [comment]
Thank you @dexcell for reporting this! I believe it was fixed in https://github.com/intellij-solidity/intellij-solidity/pull/214, but feel free to reopen if there are any remaining issues.
