### ISSUE TITLE
Plugin doesn't support solidity's `.slot` inside assembly block 

### ISSUE THREAD

**Issue by lacasian** [intellij-solidity/intellij-solidity#209]
From the solidity documentation: https://solidity.readthedocs.io/en/v0.7.2/070-breaking-changes.html
> Slot and offset of storage pointer variable x are accessed via x.slot and x.offset instead of x_slot and x_offset. 

The plugin shows there's an error on the `ds.slot` line but it should not.
![image](https://user-images.githubusercontent.com/8313779/95737297-2295d200-0c90-11eb-989d-f98ecc0b94d6.png)

`intellij-solidity` version: 2.3.1 

Thank you for the work you are doing! 🙏🏻

**Comment by SerCeMan** [comment]
Hey, @lacasian! Thank you for the report. The issues should be fixed with https://github.com/intellij-solidity/intellij-solidity/commit/8e9dc59accfaef191aa0fc7c880ec25141dc4445.
