### ISSUE TITLE
Solidity receive() and fallback() functions syntax

### ISSUE THREAD

**Issue by NickitaX** [intellij-solidity/intellij-solidity#215]
Starting from version 0.7.6 contracts which are intending to receive ETH are required to have one of the functions below:
```
receive() external payable
fallback() external payable
```
Currently plugin doesn't recognise it and highlights as a syntax error:
![image](https://user-images.githubusercontent.com/11023063/113690491-cecfe700-970e-11eb-96a3-565701e5966c.png)

Ping ping

**Comment by SerCeMan** [comment]
Hey, @NickitaX! Please provide an example of the failing code. I can't reproduce your report. 
<img width="503" alt="Screen Shot 2021-05-08 at 1 45 24 pm" src="https://user-images.githubusercontent.com/1780970/117525006-a5eb8c00-b003-11eb-8880-cff9775085ac.png">
