### ISSUE TITLE
Unicode strings aren't parsed correctly for solc 0.7.+

### ISSUE THREAD

**Issue by payprmoney** [intellij-solidity/intellij-solidity#217]
In solc 0.7 and up, unicode strings must be identified as such: `unicode'some string with unicode'` or `unicode"some string with unicode"`.

However, this plugin doesn't support that sequence properly. It gives an error like the following:

```
Error:(10, 10) '(' or '{' expected, got ''some string with unicode''
```

**Comment by SerCeMan** [comment]
Hi, @payprmoney! Thank you for reporting, this was fixed in #217, so I'll close the issue.
