### ISSUE TITLE
"bytes" type is not highlighted

### ISSUE THREAD

**Issue by decanus** [intellij-solidity/intellij-solidity#22]
The various byte types do not seem to be recognised.

**Comment by SerCeMan** [comment]
Hi, @decanus!

Thank you for the report. Please attach a sample of code and a screenshot that demonstrates the problem.

**Comment by decanus** [comment]
![image](https://user-images.githubusercontent.com/7621705/30729165-d6ea74ac-9f5d-11e7-9a8b-3cfa7643440c.png)

Notice how there is no highlighting for bytes. However there is highlighting for byte32 and other byte types with length specification
