### ISSUE TITLE
Add support for comments color scheme

### ISSUE THREAD

**Issue by crisgarner** [intellij-solidity/intellij-solidity#226]
All comments are using the same background, it would be helpful to add support for natspec color scheme using tags for the comments like other languages.

**Comment by SerCeMan** [comment]
Hey, @crisgarner! Thanks for reporting this! The support for natspec should be available in the next version (https://github.com/intellij-solidity/intellij-solidity/pull/247, https://github.com/intellij-solidity/intellij-solidity/pull/248). 
<img width="709" alt="Screen Shot 2021-09-25 at 2 13 01 pm" src="https://user-images.githubusercontent.com/1780970/134757522-0863c137-40a2-4c75-ba27-375740c8b439.png">
