### ISSUE TITLE
Support functions outside of a contract

### ISSUE THREAD

**Issue by patitonar** [intellij-solidity/intellij-solidity#227]
Since solidity [0.7.1](https://github.com/ethereum/solidity/blob/develop/Changelog.md#071-2020-09-02) functions can be [declared outside of a contract](https://docs.soliditylang.org/en/v0.8.7/contracts.html#functions) 

Example
```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.7.1 <0.9.0;

function sum(uint[] memory _arr) pure returns (uint s) {
    for (uint i = 0; i < _arr.length; i++)
        s += _arr[i];
}
````

Right now, the error `<contract definition>, <expression>, enum, import, pragma or struct expected, got 'function'` is displayed on the function

**Comment by SerCeMan** [comment]
Thanks, @patitonar! The fix is on master now. I'm planning to rewrite the grammar to make it closer to [SolidityParser.g4](https://github.com/ethereum/solidity/blob/develop/docs/grammar/SolidityParser.g4) to make it much easier to stay 100% up to date with the changes. 👍
