### ISSUE TITLE
experimental pragmas causing issues

### ISSUE THREAD

**Issue by androlo** [intellij-solidity/intellij-solidity#23]
Plugin version `2.0.2`

These pragmas are not being parsed properly:

```
pragma experimental "v0.5.0";
pragma experimental ABIEncoderV2;
```

They are needed to run the latest stuff (you can't remove citation marks around "v0.5.0" or it will throw and complain about stray arguments). Both of those will report errors in the IDE.

**Comment by androlo** [comment]
Seems `ABIEncoderV2` can be enclosed in double quotes, but removing them from `v0.5.0` will not work.

**Comment by SerCeMan** [comment]
Hey, @androlo!

Thank you for the report! The issue with quotes has been fixed.
