### ISSUE TITLE
Ethereumj download failed. I found a download address, but I don’t know if it is this. Can you see it?

### ISSUE THREAD

**Issue by yuzixuan0722** [intellij-solidity/intellij-solidity#239]
download address : http://estigia.lsi.us.es:1681/artifactory/libs-release/org/ethereum/ethereumj-core/1.7.1-RELEASE/
![image](https://user-images.githubusercontent.com/39270971/133226542-07655a9b-d6db-4d66-83b0-f6c2525e4de1.png)

If there is no problem with this file, can you modify the address in the code as soon as possible? 
**Thanks**

**Comment by yuzixuan0722** [comment]
I downloaded the zip package locally, but if the "EVM PATH" we configured is correct, the test allows solidity to report an error.

![image](https://user-images.githubusercontent.com/39270971/133231080-634ed634-ceaf-401e-bdef-08ef5d1cd804.png)
![image](https://user-images.githubusercontent.com/39270971/133231140-3f9fcf9f-fe55-41d6-864a-49d2d551205c.png)
![image](https://user-images.githubusercontent.com/39270971/133231182-e34f5829-789f-43e4-9d67-6510ec99f3a3.png)

**Comment by mbolotov** [comment]
Hi @yuzixuan0722!

Could you provide the stacktrace of error? 
I tried to run a sample contract using an EVM path directory (that's when the plugin adds an asterisk) and it works okay for me.   
Anyway, could you also describe your purpose when trying to use the launch contract feature of the plugin? It has some limitations and you may not really get much benefit from using it.

**Comment by yuzixuan0722** [comment]
I just wrote a simple test.
![image](https://user-images.githubusercontent.com/39270971/133246305-f1b4ad75-0e62-45fa-adef-e4b5cb8e9d83.png)

Below is the IDEA log, which contains the wrong stack information. Thank you for your reply!
[idea.log](https://github.com/intellij-solidity/intellij-solidity/files/7161337/idea.log)

**Comment by mbolotov** [comment]
which version of IDE do you use?
It seems that there are some compatibility issues occurred since version 2020.1 (which I tried successfully)

**Comment by yuzixuan0722** [comment]
I use IntelliJ IDEA 2021.2.1 (Ultimate Edition)

**Comment by mbolotov** [comment]
it requires some work to migrate to the new platform version, so I currently cannot debug what goes wrong.

**Comment by mbolotov** [comment]
@SerCeMan, do you have a plan to move to 2021.2 version?
I'm just tried to change the version and bumped into some compilation problems. So it's interesting how the current version could even work in 2021.2

**Comment by SerCeMan** [comment]
Hey, @mbolotov! I'm planning to update the min requirement to 2020.3 later this/next month.

**Comment by yuzixuan0722** [comment]
@mbolotov  @SerCeMan  Thanks for your answers.
