### ISSUE TITLE
Solidity syntax for FreeTON blockchain

### ISSUE THREAD

**Issue by rymkapro** [intellij-solidity/intellij-solidity#240]
Hi!
If you may know, a new FreeTON blockchain was launched a year ago.
It allows to write Solidity smart contracts but solidity language was extended a bit.
May be it would be interesting for you to write or update your plugin to support FreeTON Solidity language.

Some links for this:
[https://ton.live/landing](url)
[https://docs.ton.dev/](url)
[https://github.com/tonlabs/TON-Solidity-Compiler/blob/master/API.md](url)

There is a plugin for Visual Studio Code (may be it can be helpful)
[https://marketplace.visualstudio.com/items?itemName=podlodkin.podlodkin-freeton-vscode-solidity](url)

Thanks for your attention!

**Comment by Mododo** [comment]
There is a fork that supports Everscale (formerly FreeTON) Solidity flavor.
https://github.com/Skydev0h/intellij-solidity/releases

**Comment by mbolotov** [comment]
there is a [separate plugin](https://github.com/intellij-solidity/intellij-solidity/issues/github.com/broxus/intellij-t-sol/) that adds the support for Everscale dialect of Solidity
