### ISSUE TITLE
Comment folding is broken

### ISSUE THREAD

**Issue by cliffhall** [intellij-solidity/intellij-solidity#266]
_Using the latest Webstorm IDE with latest Solidity plugin 2.3.6._

What is going on with this comment folding? 

<img width="524" alt="Screen Shot 2021-10-22 at 12 35 45 PM" src="https://user-images.githubusercontent.com/871933/138492775-a140b28a-35d3-4a28-9c6b-0eb96cb4db31.png">
<img width="495" alt="Screen Shot 2021-10-22 at 12 36 02 PM" src="https://user-images.githubusercontent.com/871933/138492778-f053d2c6-1d39-4131-a313-477c5b4c08d2.png">

It seems to think we need control points at the NatSpec identifiers:
<img width="261" alt="Screen Shot 2021-10-22 at 12 50 52 PM" src="https://user-images.githubusercontent.com/871933/138493559-37a9639c-1f97-4ae1-9f86-61754f8fea69.png">

But that's not useful at all:
<img width="703" alt="Screen Shot 2021-10-22 at 12 51 04 PM" src="https://user-images.githubusercontent.com/871933/138493563-1c07a5ba-a8e2-452e-9a44-0f6462c60ac8.png">

I think it's specific to the Solidity plugin because it doesn't happen in in Javascript comments:
<img width="731" alt="Screen Shot 2021-10-22 at 12 48 06 PM" src="https://user-images.githubusercontent.com/871933/138493004-81272a0d-5fd9-4bfa-ba6d-ac7943d4b0c2.png">

The whole comment folds up as it should.
<img width="490" alt="Screen Shot 2021-10-22 at 12 48 14 PM" src="https://user-images.githubusercontent.com/871933/138493009-84a1811a-4519-495f-95f2-5a1d74559587.png">

**Comment by cliffhall** [comment]
Will this ever get some love? Working in Solidity with Webstorm / IntelliJ, we need to be able to collapse comments and code blocks to get the high level overview in the same way that we do in Javascript.

**Comment by cliffhall** [comment]
Any hope @SerCeMan? For teams who do proper inline documentation, this is a thorn in the side. And it looks positively ridiculous to anyone who attempts to use the functionality. It would be better to just remove the disclosure widgets altogether.

**Comment by msmyers** [comment]
I love IntelliJ and abhor VSCode, but since VSC's Solidity support is superior, I'm struggling, save me (by fixing this)!

**Comment by mbolotov** [comment]
fixed is `2.4.1` version

**Comment by cliffhall** [comment]
@mbolotov Are you sure this is fixed in `2.4.1`? I have `2.4.4` installed and it is still a problem.

<img width="654" alt="Screenshot 2024-05-15 at 11 12 33 AM" src="https://github.com/intellij-solidity/intellij-solidity/assets/871933/47120e66-202f-45aa-bbe2-2e20bf9fcab7">

<img width="619" alt="Screenshot 2024-05-15 at 11 12 42 AM" src="https://github.com/intellij-solidity/intellij-solidity/assets/871933/001570e2-aca9-4e5d-a740-e7bad30fc9ef">

<img width="753" alt="Screenshot 2024-05-15 at 11 13 48 AM" src="https://github.com/intellij-solidity/intellij-solidity/assets/871933/1a6eabd3-1372-43a7-bb67-c1308e7754b6">

**Comment by mbolotov** [comment]
agree, I was wrong.
reopened
