### ISSUE TITLE
Naming a contract the same as an inherited interface/contract crashes IDE

### ISSUE THREAD

**Issue by bit-void** [intellij-solidity/intellij-solidity#277]
If you define a contract like this:

```
import "@openzeppelin/contracts/token/ERC721/ERC721.sol";

contract ERC721 is ERC721 {}
```

intellij immediately crashes. It also crashes as soon as you boot.

**Comment by SerCeMan** [comment]
Hey, @jetaggart! Could you clarify what you mean by crashes, and if there is any way to easily reproduce this? Which IJ Solidity version, and what OS do you use? I'm struggling to reproduce the issue on the latest IJ Solidity version. 

<img width="548" alt="Screen Shot 2021-12-18 at 4 08 42 pm" src="https://user-images.githubusercontent.com/1780970/146629917-8dd08a96-7bbb-46c5-913a-48301362e041.png">

**Comment by jetaggart** [comment]
This was on MacOS, solidity 0.8.6, intellij 2021.3. The exception was a StackOverlow

**Comment by bit-void** [comment]
I'm not seeing this anymore, sorry for the red herring.
