### ISSUE TITLE
Add support for multiple "" in the same string

### ISSUE THREAD

**Issue by flow3d** [intellij-solidity/intellij-solidity#282]
Useful for long strings would be to be able to define:
```
bytes internal constant bla = "aaaaaaaaaaaaaaaaaaaaaaaaa"
                              "aaaaaaaaaaaaaaaaaaaaaaaaa";
```

Currently, it breaks the editor.

**Comment by SerCeMan** [comment]
Hey, @flow3d! This should be fixed in https://github.com/intellij-solidity/intellij-solidity/pull/284 :)
