### ISSUE TITLE
Structure stops at the contract level

### ISSUE THREAD

**Issue by Mouradif** [intellij-solidity/intellij-solidity#289]
When trying to look at the code structure, it only shows the contract name.

It should at least show each contract function, and ideally, it would also show the structs, variables and events declared.
 
![image](https://user-images.githubusercontent.com/4118825/159342707-5d6cd665-4f7d-430a-9644-b3c50c01b6d9.png)

**Comment by mbolotov** [comment]
this has been fixed in 2.4.4 version
