### ISSUE TITLE
Hanging on code changes in latest version (unreleased) introduced in #304

### ISSUE THREAD

**Issue by artdgn** [intellij-solidity/intellij-solidity#306]
I'm building from source and loading plugin from disk (in order to utilise #300), but it seems to be causing IntelliJ to hang for several seconds at a time during code edits.

Haven't observed this hanging in the official released version 2.3.8 I was initially using. Went back and forth between the versions and can confirm that the hanging is just with the new version.

Is it possible that it's caused by some other change introduced since that version? Can it be related to me loading the plugin from disk (having build it locally)?

**Comment by SerCeMan** [comment]
Hey, @artdgn! Could you attach a CPU profile which might shed some light on the issues you're observing? 

<img width="692" alt="Screen Shot 2022-05-27 at 3 06 33 pm" src="https://user-images.githubusercontent.com/1780970/170633118-85d394c6-71ba-4a75-8860-f4447e1c4bbb.png">

Would you also be able to test if the same behaviour is observed with https://github.com/intellij-solidity/intellij-solidity/pull/300? I wonder if this could be related to using resolving during highlighting.

**Comment by artdgn** [comment]
@SerCeMan 
This is what I'm seeing with with the activity monitor (I don't have all the other options you have in your screenshot, I'm guessing it's a pro version or smth)
![image](https://user-images.githubusercontent.com/29574203/170636382-7616ff31-80dc-44db-b2b7-abdbcf4c709d.png)

**Comment by artdgn** [comment]
> resolving during highlighting.

I can get the hanging to trigger during highlighting, but sometimes I just see the CPU spike with no hanging (UI still responsive).

The surest way I can trigger for now it with is editing a highlighted function call element.

**Comment by SerCeMan** [comment]
Thanks, seeing the below confirms the suspect. I'll take a look at making changes there so that highlighting doesn't depend on resolver. Thanks for reporting. 

<img width="649" alt="Screen Shot 2022-05-27 at 3 43 57 pm" src="https://user-images.githubusercontent.com/1780970/170637644-dd8d86e7-aa6e-41e8-bbf2-05daf868dd4f.png">

**Comment by artdgn** [comment]
@SerCeMan The earliest commit where I can repro the issue is actually 06b66d5fc31d99f36d4fc120b6cb03a2a7d607d7 merging #304

**Comment by artdgn** [comment]
Can confirm that cherry-picking #300 on top of #303 (without taking #304) doesn't hang.

**Comment by SerCeMan** [comment]
Hi, @artdgn! Yes, it might not be bundled by default. Would you be able to install the plugin as [described here](https://intellij-support.jetbrains.com/hc/en-us/articles/207241235-Reporting-performance-problems#CPU_Snapshot_2019_2) and attach the profile? 

<img width="910" alt="Screen Shot 2022-05-28 at 2 50 18 pm" src="https://user-images.githubusercontent.com/1780970/170810473-5f4d3776-bc4a-4cda-b577-23dbf2a25dbc.png">

Also, could you clarify what you mean by "editing a highlighted function call element"? Do you mean a rename refactoring or just changing the function name, or something else? If you could attach a video of what you're referring to, it'd be perfect, as I haven't been able to reproduce it so far.

**Comment by artdgn** [comment]
@SerCeMan I'll try to this and maybe create a minimal repro code snippet when next week. For now what worked for me is cutting out the changes made in #304 (that aren't related to syntax highlighting rules) by removing that commit and rebuilding. I'm not sure why [that code](https://github.com/intellij-solidity/intellij-solidity/pull/304/files) causes this but it's worth to think how that code may cause a freeze of the whole UI..

Also, I'm using ubuntu in case it's system dependent.

**Comment by SerCeMan** [comment]
I think I found a way to reproduce it, the interesting part is that it's only reproducible on 2022.1.1+.

**Comment by SerCeMan** [comment]
Hey, @artdgn! Could you check if https://github.com/intellij-solidity/intellij-solidity/pull/308 fixes the issue for you? I can't reproduce it anymore with the change applied.

**Comment by artdgn** [comment]
@SerCeMan yep looks great, had no issues! Thanks for the quick fix, and the great plugin!
