### ISSUE TITLE
Not working in PyCharm CE?

### ISSUE THREAD

**Issue by mbrennan** [intellij-solidity/intellij-solidity#31]
Hello,

I have PyCharm CE and installed the latest version of the plugin.  However, when I create a new file, I don't see any option to associate my .sol file with the plugin.  How can I get PyCharm CE to recognize .sol files?

**Comment by SerCeMan** [comment]
Hi, @mbrennan!

I just tried and I was able to install the plugin without any problem. Is it possible that you had created `.sol` association with some other editor before installing the plugin? If so, you might need to create the association manually:

![screen shot 2017-11-20 at 10 22 22 am](https://user-images.githubusercontent.com/1780970/32996869-bd48b1dc-cddc-11e7-8e29-064e41eddc1d.png)

**Comment by SerCeMan** [comment]
@mbrennan Please reopen the issue if you're still experiencing the problem
