### ISSUE TITLE
structue has no indent after formatting the code.

### ISSUE THREAD

**Issue by zeroarst** [intellij-solidity/intellij-solidity#314]
What is current behavior:
![image](https://user-images.githubusercontent.com/1834837/180591871-0dcc1a54-0d52-4d9a-9c46-5d3b9a430e71.png)
![image](https://user-images.githubusercontent.com/1834837/180591884-71137496-0c73-4e55-8c9b-5ddde7d56927.png)
![image](https://user-images.githubusercontent.com/1834837/180592020-1cba00e7-d642-413b-b84c-f31bf3d32004.png)

What is the expected behavior:
![image](https://user-images.githubusercontent.com/1834837/180591859-2baa22ee-8802-4efc-a596-1f23928a3323.png)
![image](https://user-images.githubusercontent.com/1834837/180591862-96a74a80-bb51-4b2a-972d-23dc410f890a.png)
![image](https://user-images.githubusercontent.com/1834837/180592029-88d19ae5-0853-45d4-92c6-5d12213063d0.png)

Feels like as long as `{` and `}` appear, the indent will be removed.

**Comment by lebed2045** [comment]
I can confirm the same issue. Perhaps at least some .editorconfig settings would be nice to have.

**Comment by VlodkoMr** [comment]
Hello, also waiting to some solution...
