### ISSUE TITLE
support single-quoted unicode

### ISSUE THREAD

**Issue by julesGoullee** [intellij-solidity/intellij-solidity#315]
In opposit to https://github.com/intellij-solidity/intellij-solidity/issues/217, unicode support hasn't been fixed, still as described in this issue.

**Comment by SerCeMan** [comment]
Hey, @julesGoullee! Could you provide a test case so that I can understand what is not working?

**Comment by SerCeMan** [comment]
Ah, I see, you left a comment in https://github.com/intellij-solidity/intellij-solidity/issues/316#issuecomment-1193097620, I'll take a look.

**Comment by julesGoullee** [comment]
Hey,
`unicode"😀"` looks correct, and `unicode'😀'` is badly intepreted

<img width="555" alt="Screenshot 2022-07-24 at 11 18 21" src="https://user-images.githubusercontent.com/6892100/180640556-9cc436c8-fdd0-433f-b1bc-2d100c689430.png">

**Comment by julesGoullee** [comment]
Awesome thx!

**Comment by julesGoullee** [comment]
@SerCeMan I have bad news, the fix creates a side effect. You can test by yourself by changing the double quote here https://github.com/hydnsec/hydn-seal/blob/master/contracts/HYDNSeal.sol#L38, it creates a syntax error here https://github.com/hydnsec/hydn-seal/blob/master/contracts/HYDNSeal.sol#L85
