### ISSUE TITLE
Error when using fallback function with data

### ISSUE THREAD

**Issue by chrisffm** [intellij-solidity/intellij-solidity#316]
When I add a fallback function to my contract, which receives and returns data, I get an error.

`fallback(bytes calldata _input) external returns(bytes memory)` leads to the following error:

`<state variable declaration>, constructor, enum, error, event, fallback, function, import, modifier, pragma, receive, struct, type, using or '}' expected, got 'fallback'`

while `fallback() external` works fine

**Comment by julesGoullee** [comment]
Update:
`unicode'😀'` is badly interpreted and `unicode"😀"` work.

**Comment by SerCeMan** [comment]
Hey, @chrisffm! Thank you for reporting, this should be fixed in https://github.com/intellij-solidity/intellij-solidity/pull/319.
