### ISSUE TITLE
Destructuring inside a Try Catch block shows error

### ISSUE THREAD

**Issue by kevupton** [intellij-solidity/intellij-solidity#321]
This error only happens when values are destructured from a method call inside a try catch block

```solidity
contract A {
    function runSomething(uint256 val) external {

    }
}

contract Test {

    A a;

    function tryCatch() external {
        uint256 b = 2;
        uint256 c;
        uint256 d;

        try a.runSomething(b) {
            (c, d) = _doSomething();
        } catch(bytes memory error) {
            (c, d) = _doSomethingElse(error);
        }
    }

    function _doSomething() private returns (uint256, uint256) {
        return (1, 2);
    }

    function _doSomethingElse(bytes memory error) private returns (uint256, uint256) {
        return (3, 4);
    }
}
```

This block of code shows an error in the editor, 

![image](https://user-images.githubusercontent.com/2093615/183535608-75e148a7-7cc0-45e3-89e6-7d0821a5e0e4.png)

But compiles ok.
![image](https://user-images.githubusercontent.com/2093615/183535635-333be747-7261-43cf-80f8-be136db01aad.png)

It would also be nice to add some syntax highlighting for try catch 😛 

--- 

## Things that work:

![image](https://user-images.githubusercontent.com/2093615/183535998-e07fe5f6-6c20-45e0-823d-540ee312180b.png)
![image](https://user-images.githubusercontent.com/2093615/183536039-8dd25a35-fcca-4c03-94f8-b62426425793.png)
![image](https://user-images.githubusercontent.com/2093615/183536082-ddf51d71-398e-4e29-87be-e9884c06e859.png)

**Comment by SerCeMan** [comment]
Hey, @kevupton! Thank you reporting! The issue should be fixed in https://github.com/intellij-solidity/intellij-solidity/pull/340. It was due to early expression pinning in the parser where it'd thinking that `runSomething(b) {` is all a part of the initial expression.
