### ISSUE TITLE
Incorrect parsing of this multiline-comment-style

### ISSUE THREAD

**Issue by Minh-Trng** [intellij-solidity/intellij-solidity#329]
multiline-comments of the following style are syntactically correct, but lead to parsing and code navigation being broken

```
/*//////////////////////////////////////////////////////////////
                                URI LOGIC
//////////////////////////////////////////////////////////////*/
```

**Comment by astralblue** [comment]
+1.  farcasterxyz/contracts use this syntax.  Workaround: Replace `/*//` -> `/* /` and `//*/` -> `/ */`

**Comment by SerCeMan** [comment]
Hey, @Minh-Trng! Thank you for reporting. The issues was due to the lexer treating `/*/` as a valid block comment, and it should be fixed in https://github.com/intellij-solidity/intellij-solidity/pull/339. 👍
