### ISSUE TITLE
Syntax for Everscale (TON) blockchain

### ISSUE THREAD

**Issue by ser0ja** [intellij-solidity/intellij-solidity#335]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/5020923/201310079-d52647fb-fd53-4436-ba8d-7d2cb6017931.png">
<img width="271" alt="image" src="https://user-images.githubusercontent.com/5020923/201310734-9eca7d96-8916-4208-9a66-bb0b5d955bfb.png">
<img width="254" alt="image" src="https://user-images.githubusercontent.com/5020923/201310777-13e8bf78-6b4e-4fca-be4f-e8c28bc0c98c.png">

-----
<img width="264" alt="image" src="https://user-images.githubusercontent.com/5020923/201309941-189ad0a2-e2d9-4f7b-9aac-fc90a7e457c9.png">

[API.md#keyword-static](https://github.com/tonlabs/TON-Solidity-Compiler/blob/master/API.md#keyword-static)

-----
<img width="579" alt="image" src="https://user-images.githubusercontent.com/5020923/201310549-280fbc28-d11d-4dc3-b580-06263bdcc53f.png">

[API.md#return](https://github.com/tonlabs/TON-Solidity-Compiler/blob/master/API.md#return)

-----
<img width="407" alt="image" src="https://user-images.githubusercontent.com/5020923/204744809-8743aa4e-ef18-4823-ae52-374382ee9efc.png">

[API.md#range-based-for-loop](https://github.com/tonlabs/TON-Solidity-Compiler/blob/master/API.md#range-based-for-loop)

-----
<img width="383" alt="image" src="https://user-images.githubusercontent.com/5020923/204768577-dec720a4-bcb2-4e38-a276-757bd5594990.png">

[API.md#tvmslicedecode](https://github.com/tonlabs/TON-Solidity-Compiler/blob/master/API.md#tvmslicedecode)

Thanks for your time

**Comment by mbolotov** [comment]
there is a [separate plugin](github.com/broxus/intellij-t-sol/) that adds the support for Everscale dialect of Solidity
