### ISSUE TITLE
Causes intellij indexing to randomly hang

### ISSUE THREAD

**Issue by silasdavis** [intellij-solidity/intellij-solidity#338]
I've had an issue with intellij where indexing was hanging - indefinitely - on seemingly random files. The IDE was responsive but mostly unusable because indexing didn't finish.

I have noticed that removing this Solidity plugin fixes the issue.

I am working in a large monorepo (~5GB) with typescript/rust/Solidity. The Solidity plugin has seemed to struggle with indexing in a way typescript does not. For example navigating to a symbol can takes tens of seconds. I wonder if there is some sub-optimal behaviour when dealing with a large index.

I can share IDE logs or something else if that helps.

**Comment by SerCeMan** [comment]
Hi, @silasdavis! The issue is likely to be related to https://github.com/intellij-solidity/intellij-solidity/issues/317. Do you know if there is a way to reproduce it? I haven't been able to reproduce the issue myself.
