### ISSUE TITLE
multiple Inheritance code completion

### ISSUE THREAD

**Issue by yvvw** [intellij-solidity/intellij-solidity#350]
os: macos
webstorm version: 2022.3.3
plugin version: 2.3.11

I'm glad to be using your plugin. but i have encountered the following problem. this causes the vm's method in the Forge test module to not be fully displayed.

<img width="438" alt="image" src="https://user-images.githubusercontent.com/15168529/224939430-f8cb90fd-9d32-4536-9ef5-56925e2629f7.png">
<img width="594" alt="image" src="https://user-images.githubusercontent.com/15168529/224937257-1a9a0c59-43c5-4c7c-8471-890e31cc024e.png">
<img width="343" alt="image" src="https://user-images.githubusercontent.com/15168529/224937344-5d466b11-b1f5-448b-a1cc-cc516fc503ed.png">

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Test.sol";

contract A1 {
    function a1() public {
        console2.log("a1");
    }
}
contract A2 is A1 {
    function a2() public {
        console2.log("a2");
    }
}
contract B1 {
    A1 private a = new A1();
}
contract B2 {
    A2 internal a = new A2();
}
contract C is B1, B2 {
    function invoke() public {
        a.a1();
        a.a2();
        a.
    }
}
contract ForgeTest is Test {
    function testC() public {
        C c = new C();
        c.invoke();
    }
}
```

**Comment by jonahcui** [comment]
This is because the plugin parses the super contracts from left to right. But in solidity doc, the priority is from right to left. I submitted a pr to fix this problem.
