### ISSUE TITLE
multiple values return is marked as an error

### ISSUE THREAD

**Issue by adridadou** [intellij-solidity/intellij-solidity#4]
If I return more than one value, for ex: return (1, 23, 5) and the return type is returns (uint, uint, uint),
It marks it as illegal. It looks like the plugin doesn't recognize multiple values return statement as valid

**Comment by SerCeMan** [comment]
Hey, @adridadou! It has already been fixed but hasn't been released yet.

https://github.com/intellij-solidity/intellij-solidity/commit/6373562886dea7fb524739a1ed072e846db4ccbc

**Comment by adridadou** [comment]
Oh ok sorry. I only tried the released version :) When is the next release?

**Comment by SerCeMan** [comment]
We'll release it some day next week. Can't say for sure, it depends on how long the approval will take :)

**Comment by SerCeMan** [comment]
Hey, @adridadou! 

The new version has finally been approved. This time it took longer than I expected. Please check that your problem is fixed and feel free to reopen the issue if it's not.
