### ISSUE TITLE
Ctrl+Click on IShortInterfaceName does not follow to ILongInterfaceName when importing it using `as` 

### ISSUE THREAD

**Issue by XAudit174176** [intellij-solidity/intellij-solidity#406]
Hi there, and honestly thanks for your efforts working on this great extension 💙 

<h3>Short Description</h3>

When importing an interface `as` sth, the extension doesn't understand that it is the same as the interface itself, so it also cannot identify all sub-functions and variables... and Ctrl + Click does not work

<h3>Example</h3>

- Imagine this is the interface module file called `IArbitrumBranchPort.sol` (that we wanna import it into our contract):

 
```solidity
pragma solidity ^0.8.0;

interface IArbitrumBranchPort {
    function depositToPort(address _depositor, address _recipient, address _underlyingAddress, uint256 _amount) external;
}
// ...
```
<br>

- Now imagine we have our contract sth like this:

```solidity
pragma solidity ^0.8.0;
import {IArbitrumBranchPort as IArbPort} from "./interfaces/IArbitrumBranchPort.sol";
contract ArbitrumBranchBridgeAgent{

    function depositToPort(address underlyingAddress, uint256 amount) external payable lock {
            IArbPort(localPortAddress).depositToPort(msg.sender, msg.sender, underlyingAddress, amount);
     }
}
// ...
```

The problem is that if we import without using `as IArbPort` and just use `IArbitrumBranchPort` itself, the extension can find it and its sub items:

```solidity
// ...
    function depositToPort(address underlyingAddress, uint256 amount) external payable lock {
            IArbitrumBranchPort(localPortAddress).depositToPort(msg.sender, msg.sender, underlyingAddress, amount);
     }
// ...
```

But when using the short form (like `IArbPort(localPortAddress).depositToPort...`), the extension does not understand that these are the same 

Thanks again, hope you the best

**Comment by SerCeMan** [comment]
Hey, @XAudit174176! Thank you for reporting the issue, it should be fixed in https://github.com/intellij-solidity/intellij-solidity/pull/407.
