### ISSUE TITLE
it can't report the error after I have commented a variable 

### ISSUE THREAD

**Issue by lijian12345** [intellij-solidity/intellij-solidity#408]
![image](https://github.com/intellij-solidity/intellij-solidity/assets/26590220/48a10d98-8268-4240-9e9d-5179bdd4e4aa)

**Comment by mbolotov** [comment]
this is fixed in 2.4.4 version. See the `Name cannot be resolved` inspection and ensure it's enabled:
![image](https://github.com/intellij-solidity/intellij-solidity/assets/19785715/81a08760-83bc-458d-80a8-0ed1290bde03)
