### ISSUE TITLE
Current version [2.4.2] not compatible with current IntelliJ [222.3345.118]

### ISSUE THREAD

**Issue by arne-fuchs** [intellij-solidity/intellij-solidity#414]
Hello,
I wanted to write some tests and needed to add the solidity plugin as dependency. I've tried adding the latest version but get the following error:
```org.jetbrains.intellij.BuildException: Plugin 'me.serce.solidity:2.4.2' is not compatible to: IU-222.3345.118```
If I downgrade the plugin to 2.3.2 it compiles but get compatibility issues with kotlin.

Any solution to this?

**Comment by SerCeMan** [comment]
Hi, @arne-fuchs! 

The required version of IJ is IDEA 2022.2.5. I believe it's the latest IJ version on the 2022.2.x range so I recommend bumping `222.3345.118` to `222.4554.10` in the plugin that you work on. 

https://github.com/intellij-solidity/intellij-solidity/blob/cab0eebed73a33f44498750d917f093ed0a5972e/src/main/resources/META-INF/plugin.xml#L48-L53

**Comment by arne-fuchs** [comment]
Hi @SerCeMan 
Thanks for the answer!
I am currently working of a fork from the intellij-hardhat plugin to implement code completion for javascript for the smart contracts written in solidity. 
Currently the compatibility is described as followed in the gradle.properties:
```
pluginSinceBuild = 222
pluginUntilBuild = 233.*
```

So I guess I only need to change that? Can something brake if I change the compatibility?

**Comment by arne-fuchs** [comment]
I kinda figured it out. Thanks for the help!
