### ISSUE TITLE
not work with solidity version 0.4.17

### ISSUE THREAD

**Issue by keeper402** [intellij-solidity/intellij-solidity#442]
these codes not work:
```
contract ERC20Basic {
    uint256 public _totalSupply;

    function totalSupply() public constant returns (uint256);

    function balanceOf(address who) public constant returns (uint256);

    function transfer(address to, uint256 value) public;

    event Transfer(address indexed from, address indexed to, uint256 value);
}

```

![Snipaste_2024-06-23_00-00-43](https://github.com/intellij-solidity/intellij-solidity/assets/170750475/94b8b573-175e-444a-bf8d-6ae70c3422b9)

**Comment by mbolotov** [comment]
yes, the support for `constant` modifier of a function has been dropped in the plugin. 
you can replace it using the `view` modifier:
![image](https://github.com/intellij-solidity/intellij-solidity/assets/19785715/c4441b8f-d760-4a26-a09b-3e54783771b1)

**Comment by keeper402** [comment]
Are solidity old version keywords all droped in this plugin? If not, is there a list about it?

**Comment by mbolotov** [comment]
No, AFAIK, `constant` only was dropped

**Comment by keeper402** [comment]
Thank you for your help.
