### ISSUE TITLE
Unable to set indentation size

### ISSUE THREAD

**Issue by danellis** [intellij-solidity/intellij-solidity#49]
In Editor -> Code Style -> Solidity, change the indent size has no effect (it's stuck at 2). Changing the number there doesn't register as a change (i.e. "Apply" isn't enabled, and the section isn't highlighted in the prefs navigation).

**Comment by steffel-monaco** [comment]
By default the value is 4 I changed to 2 but It's not changing the preview and I can't click the apply button.

<img width="1074" alt="screen shot 2018-04-12 at 2 56 20 pm" src="https://user-images.githubusercontent.com/38199889/38661036-01091948-3e62-11e8-9302-46d71dcd978b.png">

**Comment by SerCeMan** [comment]
Hey, @steffel-monaco, @danellis! Please make sure that this is not a problem with the selected scheme, I can't reproduce it.

**Comment by jelanijohn** [comment]
I'm also having this problem. On Ubuntu 16.0.4. using the default scheme. I try to hit apply in these settings but when i open up the code style config again it goes back to default settings.
![example](https://user-images.githubusercontent.com/589328/38881884-e0faa706-4236-11e8-89b9-ca03cb056899.png)

**Comment by SerCeMan** [comment]
I reproduced the problem with the latest IntelliJ,
