### ISSUE TITLE
Bug: invalid code reformatting

### ISSUE THREAD

**Issue by bshevchenko** [intellij-solidity/intellij-solidity#5]
For instance I have code:
---
![2017-03-28 1 19 28](https://cloud.githubusercontent.com/assets/1531049/24380577/c235e95a-1354-11e7-803a-fa6fbff92518.png)

When I use Code Reformat with intellij-solidity plugin I get:
---
![2017-03-28 1 20 06](https://cloud.githubusercontent.com/assets/1531049/24380587/cc6591dc-1354-11e7-8a17-68626ac863e2.png)

Bugs
---
1. Excess empty string before imports
2. Excess empty string before 'contract' keyword
3. Excess empty string before each mapping/variable, but it will be great if you leave empty string after events and before if they are located not right after 'contract' keyword line
4. All comments are now without indents

**Comment by SerCeMan** [comment]
Hi, @bshevchenko!

As far as I can see all the problems you mentioned have been fixed by the https://github.com/intellij-solidity/intellij-solidity/pull/32. Please open a new issue for other formatting problems :)
