### ISSUE TITLE
Code Generation?

### ISSUE THREAD

**Issue by RioVic** [intellij-solidity/intellij-solidity#51]
Is there a mechanism in this plugin to generate code from the Abstract Syntax Tree created by the parser?

**Comment by SerCeMan** [comment]
Hi, @RioVic!

No, there is nothing like this at the moment, but you're always welcome to hack on this. Although, I'm sure that using something will `web3j` can be easier.

**Comment by SerCeMan** [comment]
Hey, @RioVic! I hope the question is answered, so I'm closing the ticket. There is also an open PR, https://github.com/intellij-solidity/intellij-solidity/pull/66 now.
