### ISSUE TITLE
emit is not keyword, and compiles error when appeared.

### ISSUE THREAD

**Issue by godmonth** [intellij-solidity/intellij-solidity#55]
as topic

**Comment by SerCeMan** [comment]
Hi, @godmonth!

> Please attach the screenshot for every issue if possible. It will make the issue much clearer and easier to understand.

**Comment by godmonth** [comment]
![image](https://user-images.githubusercontent.com/757024/37328094-cbf56e46-26d3-11e8-9138-afb9cafcebd6.png)

**Comment by SerCeMan** [comment]
@godmonth, Thanks for the report, support for `emit` is added in https://github.com/intellij-solidity/intellij-solidity/commit/70c96b9f6e46d1b25c00ff3e7dc7ad7085258822
