### ISSUE TITLE
emit keyword not supported

### ISSUE THREAD

**Issue by etherwaifu** [intellij-solidity/intellij-solidity#59]
Since Solidity 0.4.21, `emit` keyword is recommended to be used before emitting events
https://github.com/ethereum/solidity/releases/tag/v0.4.21

For example

`emit TokenCreated(tokenId);`

In the current version of the plugin, it will be a syntax error.

**Comment by SerCeMan** [comment]
Hey, @etherwaifu!

This was fixed in https://github.com/intellij-solidity/intellij-solidity/commit/70c96b9f6e46d1b25c00ff3e7dc7ad7085258822

**Comment by kingjerod** [comment]
Can a new release be done for this?

**Comment by SerCeMan** [comment]
I'm going to release a new version soon, in the meantime, you can build the plugin from the master branch, https://github.com/intellij-solidity/intellij-solidity#build

**Comment by OsoianMarcel** [comment]
We are waiting for new release (emit support) 👍
