### ISSUE TITLE
Import file hint doesn't work as expected

### ISSUE THREAD

**Issue by k-misztal** [intellij-solidity/intellij-solidity#64]
Import file hint pops up even though a file is properly imported. The problem occurs when I use multiple inheritances and I define a structure in the root contract. For instance: 

```
contract A {
  struct MyStruct
}
```

```
import "A.sol";

contract B is A {
}
```

```
import "B.sol";

contract C is B {
   MyStruct A; //My struct is correctly imported as its part of B
}
```

In contract `C` `MyStruct` is correctly imported. Even though plugin prompts me to import `A` contract. Moreover, even if I do that, it keeps prompting me about that.

**Comment by 0v1se** [comment]
Thanks. I will take a look

**Comment by 0v1se** [comment]
@SerCeMan, SolContractOrLibMixin.collectSupers should find all supers for contract?

Currently it doesn't find A as super contract for C (from provided source code)
Is it a bug in collectSupers? Or should we implement new method for this?

**Comment by SerCeMan** [comment]
Hey, @0v1se. I believe it's a bug in `collectSupers`

**Comment by 0v1se** [comment]
@SerCeMan ok, I'll fix it in some days if you don't ming
