### ISSUE TITLE
Error Building

### ISSUE THREAD

**Issue by fredfortier** [intellij-solidity/intellij-solidity#74]
Here is what I get when building on MacOS X.

```
$ ./gradlew buildPlugin

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '10.0.1'.
```

I tried upgrading the JDK, changing JAVA_HOME, etc.

**Comment by SerCeMan** [comment]
Hey, @fredfortier!

It looks like you're building with JDK 10, it seems like this version of the gradle plugin doesn't support it. Try building with JDK 8/9.

**Comment by mbolotov** [comment]
Hey, guys!

JDK 9 will fail as well, see this
https://discuss.gradle.org/t/could-not-determine-java-version-from-9-0-1/24457

I also tried it by myself:

> mbolotovmac:intellij-solidity mbolotov$ ./gradlew -Dorg.gradle.java.home='/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home' build 
>
> FAILURE: Build failed with an exception.
>* What went wrong:
Could not determine java version from '9.0.1'.

**Comment by SerCeMan** [comment]
Hey, @fredfortier! I updated gradle to 4.7 which should support JDK10 in https://github.com/intellij-solidity/intellij-solidity/commit/d4a67d2f570a853320db5d64dbbbdf2392ee1d79. 

Although, it's not tested and I can't guarantee that it works properly, so I recommend using JDK8 for this project.
