### ISSUE TITLE
Make it possible to customize the syntax highlighting in the settings

### ISSUE THREAD

**Issue by IAMtheIAM** [intellij-solidity/intellij-solidity#8]
Great plugin. How do we get intellij to turn on the Syntax Highlighting?

![solidity_intellij_2017-06-13_1508](https://user-images.githubusercontent.com/13709948/27106884-2e2bf816-504a-11e7-8026-fe2852b6bfa5.png)

Also, it would be great to be able to customize the syntax highlighting in the Settings > Editor > Colors & Fonts menu
![solitidy_customize_2017-06-13_1509](https://user-images.githubusercontent.com/13709948/27106944-7726fa52-504a-11e7-8148-a25b80dd71ac.png)

**Comment by SerCeMan** [comment]
Hi, @IAMtheIAM!

That functionality isn't implemented currently.

**Comment by SerCeMan** [comment]
Hi, @IAMtheIAM!

Please ignore the previous answer, I misunderstood you. 

> How do we get intellij to turn on the Syntax Highlighting?

It turned on, I think your theme has the same colour for different elements. Can you enable the `darkula` theme temporarily to check if the theme is the problem?

> Also, it would be great to be able to customize the syntax highlighting in the Settings > Editor > Colors & Fonts menu

That functionality is not implemented yet.

**Comment by IAMtheIAM** [comment]
Hi. I deleted custom theme plugin, restarted, enable Darcula theme - looks same as my original screenshot. if I use IntelliJ default theme, look like this:

![solid_2017-06-14_1316](https://user-images.githubusercontent.com/13709948/27152730-ac949212-5103-11e7-8fa1-d815f56b1235.png)

Hmm, still no syntax highlighting expect for `keywords`

**Comment by IAMtheIAM** [comment]
I was using Intellij 2016.2 - Now Using 2017.1 with same results.

**Comment by dzarezenko** [comment]
@IAMtheIAM , looks like I see what you mean. The reason is grammar, a lot of lexems detects like __keyword__ in terms of IDEA and local variables and parameters detects all like local variables. Contract name is not detects like class name etc.

I hope this will be changed in future, as I used sublime before and migrate to IDEA. I hope it will be possibility to set the same colors in future.

**Comment by brawaga** [comment]
@SerCeMan, BTW, how to turn on syntax highlighting? Seems it does not automatically associate .sol files with the extensions, but even if I right click the file and select ‘Mark as Solidity’ in the context menu, it remains in default colors and even keywords aren't highlighted. I tried to reinstall the extension and some older versions too, nothing changes. Hence it does not allow debug, and without any syntax highlight support the extension look useless.

**Comment by SerCeMan** [comment]
@brawaga Hi! The issue title is misleading, the plugin associates `*.sol` files automatically. It might not work for you if you've previously tried to associate `*.sol` with something else. You can change that or add an association manually in the IntelliJ settings (`Editor->File Types->Solidity`).

**Comment by brawaga** [comment]
Now works fabulously. Guess all problems went from lack of RAM, I was running some heavy software in parallel, that's why the plugin broke down. After freeing and webStorm restart all started to work fine.

**Comment by SerCeMan** [comment]
The colour scheme panel has been implemented. I'm closing this issue now; please open a new one if needed.
