### ISSUE TITLE
How to compile/execute?

### ISSUE THREAD

**Issue by bongkokwei** [intellij-solidity/intellij-solidity#85]
Hi all,

I'm using ver 2.1.0 and I still cannot figure out how to compile the code.

Cheers

**Comment by mbolotov** [comment]
Hi @bongkokwei!

It's likely you are using an IDE without a built-in 'build project' action (like WebStorm, PhpStorm or PyCharm). Right?
I suppose they just have no the building model inside which the solidity plugin can utilize to build solidity code.

We have added a separate menu action to call the solidity compiler in such a case. The action is placed under 'Other' menu item (when no 'Build' one present).
This change is currently in the master branch and **will be included in the next plugin version**.

As for executing solidity - unfortunately, it requires the IDE to have some java modules inside. So this action will not work in your IDE either. 

Both compile/execute works for the 2.1.0 version in Intellij IDEA.

**Comment by jecction2017** [comment]
i use IntelliJ IDEA 2018.1.4 (Ultimate Edition), but i cannot also figure out how to compile the code.

**Comment by mbolotov** [comment]
Hey, @jecction2017 

Solidity compilation in 2.10 is turned on automatically when you configure the ethereumj bundle (see solidity settings in the global preferences). The plugin will use the solc compiler packaged inside the bundle. 
So when you enable ethereumj, plugin will do compile your solidity files as a part of the common (java) build process.

Please note that in the next plugin version those settings will be slightly redesigned and improved

**Comment by mbolotov** [comment]
`solc` support was removed from the plugin
