### ISSUE TITLE
Is it possible to debug solidity in intellij IDE?

### ISSUE THREAD

**Issue by tsycnh** [intellij-solidity/intellij-solidity#88]
I am currently using Pycharm as my solidity editor, is it possible to debug solidity source code just like python?

**Comment by mbolotov** [comment]
Hey, @tsycnh!
Debug is not now possible for solidity code. The usual way of providing debug capability requires a complex support from the VM (runtime) side. 

Also, I know that the truffle framework provides a way to debug on the history of transactions (
http://truffleframework.com/docs/getting_started/debugging )
We may look into it to see if we can support this feature directly from IDE

**Comment by tsycnh** [comment]
@mbolotov thanks very much. I also did my research, there is very little solution for solidity right now, especially for IDE. I checked this http://truffleframework.com/blog/announcing-full-portable-solidity-debugger which said will support IDE debugging some time. Again thanks for the plugin.

**Comment by TRileySchwarz** [comment]
@tsycnh We've have just written an article on how to do this.

https://medium.com/@TRileySchwarz/debugging-solidity-smart-contracts-inside-of-the-intellij-ide-5b97d857143d

**Comment by tsycnh** [comment]
@TRileySchwarz Great Article! Solved my problem perfectly!
