### ISSUE TITLE
byte32 et al (not a valid type) highlights, but bytes32 et al (a valid type) does not

### ISSUE THREAD

**Issue by mkoistinen** [intellij-solidity/intellij-solidity#9]
Title says it all.

**Comment by SerCeMan** [comment]
Hi, @mkoistinen!

Can you provide an example just to make sure that I understood you correctly

**Comment by mkoistinen** [comment]
Sure!
![image](https://user-images.githubusercontent.com/615759/27709628-ca21c94c-5cea-11e7-9a5d-f8021acc57b3.png)

**Comment by SerCeMan** [comment]
I'm not sure if that the best possible implementation, but currently it works as expected. 
**byte32** is a primitive type whereas **bytes32** is an array. Probably, it would make sense to make it the same colour as contract references.

**Comment by SerCeMan** [comment]
Feel free to reopen the issue if you have any questions.
