### ISSUE TITLE
new Library "ethereumj" is added to every project if I enable solc to build project

### ISSUE THREAD

**Issue by 0v1se** [intellij-solidity/intellij-solidity#93]
When I download EthereumJ, "ethereumj" library is added to every project. This is not an option for Java projects. Ethereumj uses outdated libraries (jackson, spring etc.) so adding this library breaks compilation almost for every my project.

Why library is added to project? Is there any other way?
Also, when I disable "Enable solc to build project" this library is added to projects anyway.

**Comment by 0v1se** [comment]
closed by mistake

**Comment by SerCeMan** [comment]
Hey, @0v1se! Can you give an example of how the library is added? If it gets added to the classpath then yes, we definitely need to fix this.

**Comment by mbolotov** [comment]
Hey, guys!

The initial idea about adding this library was to simplify user actions for running the generated java wrappers. 

There is a checkbox to control the behavior of adding ethereumj library in the solidity settings. 
However, there is a bug in the code that makes impossible to disable it now :)
I will fix this and probably make this option is disabled by default.

**Comment by 0v1se** [comment]
@SerCeMan Yes, it's added to the classpath now.
@mbolotov It's added even if "Generate java stubs for contracts during compilation" is turned off

**Comment by mbolotov** [comment]
`solc` support was removed from the plugin
