### ISSUE TITLE
compiling solidity code

### ISSUE THREAD

**Issue by donfrigo** [intellij-solidity/intellij-solidity#97]
Hello,

Thank you for enabling code compilation for intelliJ it is a much needed feature :)
That being said, I wasn't able to run the code even though I have install ethereumj through intellij ultimate edition. Once I press run, I get a module not specified error. What could be the problem? Thanks!

**Comment by mbolotov** [comment]
Hi, @donfrigo!
Can you choose the module manually in the combo-box?

**Comment by donfrigo** [comment]
When I go to edit configurations, I have no modules under use classpath as module, if that is what you are referring to :)

**Comment by mbolotov** [comment]
`solc` support was removed from the plugin
